# Generated by Django 4.1.2 on 2022-10-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users_photos/full_photos",
                        verbose_name="full photo",
                    ),
                ),
                (
                    "preview_photo",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="users_photos/full_photos",
                        verbose_name="full photo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("name", models.CharField(max_length=64)),
                ("is_single", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "album",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "artist",
            },
        ),
        migrations.CreateModel(
            name="MusicType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, unique=True)),
            ],
            options={
                "db_table": "music_type",
            },
        ),
        migrations.CreateModel(
            name="ArtistProfile",
            fields=[
                (
                    "full_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users_photos/full_photos",
                        verbose_name="full photo",
                    ),
                ),
                (
                    "preview_photo",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="users_photos/full_photos",
                        verbose_name="full photo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="artist.artist",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "artist_profile",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("name", models.CharField(max_length=64)),
                ("file", models.FileField(upload_to="")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="artist.album",
                    ),
                ),
            ],
            options={
                "db_table": "song",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                db_table="artist_album", related_name="albums", to="artist.artist"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="music_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artist.musictype",
            ),
        ),
    ]
