# Generated by Django 4.1.2 on 2022-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
