# Generated by Django 4.1.2 on 2022-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0003_artist_groups_artist_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="full_photo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="album",
            name="preview_photo",
            field=models.ImageField(
                blank=True,
                default="",
                editable=False,
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="artist",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="full_photo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="preview_photo",
            field=models.ImageField(
                blank=True,
                default="",
                editable=False,
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
    ]
