# Generated by Django 4.1.2 on 2022-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="full_photo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playlist",
            name="preview_photo",
            field=models.ImageField(
                blank=True,
                default="",
                editable=False,
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_photo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preview_photo",
            field=models.ImageField(
                blank=True,
                default="",
                editable=False,
                upload_to="users_photos/full_photos",
                verbose_name="full photo",
            ),
            preserve_default=False,
        ),
    ]
